trigger:
- main

pool:
  name: default

steps:
- script: |
    dir 
    cd terraform
    dir
    echo %PATH%
    terraform init
    terraform plan -auto-approve
    terraform apply -auto-approve
  displayName: 'Terraform init and apply'
- task: CmdLine@2
  inputs:
    script: 'dir'

- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: 'app/*'
    TargetFolder: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  condition: succeededOrFailed()

- task: Docker@2
  inputs:
    containerRegistry: 'acrconnection'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
  displayName: 'Docker build and push to ACR'
  

